package mib1;

import java.text.ParseException;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.SimpleDateFormat;  
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 *
 * @author Jesper
 */
public class agentAlien extends javax.swing.JFrame {
    private static InfDB idb;
 
    /**
     * Creates new form agentAlien
     */
    public agentAlien(InfDB idb) {
        initComponents();
         this.idb = idb;
        valLBL.setVisible(true);
        valLBL.setText("Ange antal boogies:");
        
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAddAlien = new javax.swing.JLabel();
        dateLBL = new javax.swing.JLabel();
        dateVal = new javax.swing.JTextField();
        nameLBL = new javax.swing.JLabel();
        nameVal = new javax.swing.JTextField();
        passLBL = new javax.swing.JLabel();
        phoneLBL = new javax.swing.JLabel();
        phoneVal = new javax.swing.JTextField();
        platsLBL = new javax.swing.JLabel();
        platsVal = new javax.swing.JTextField();
        chefLBL = new javax.swing.JLabel();
        chefVal = new javax.swing.JTextField();
        saveBTN = new javax.swing.JButton();
        tbxBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passVal = new javax.swing.JPasswordField();
        comboBoxRas = new javax.swing.JComboBox<>();
        txtRas = new javax.swing.JLabel();
        valLBL = new javax.swing.JLabel();
        textVal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAddAlien.setText("Lägg till Alien:");

        dateLBL.setText("Registreringsdatum");

        nameLBL.setText("Namn");

        passLBL.setText("Lösenord");

        phoneLBL.setText("Telefon");

        platsLBL.setText("Plats (ID)");

        chefLBL.setText("Ansvarig agent ");

        saveBTN.setText("Spara");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        tbxBTN.setText("Tillbaka");
        tbxBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxBTNActionPerformed(evt);
            }
        });

        jLabel1.setText("(YYYY-MM-DD)");

        jLabel2.setText("(ID)");

        passVal.setText("jPasswordField1");

        comboBoxRas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boglodite", "Squid", "Worm" }));
        comboBoxRas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxRasActionPerformed(evt);
            }
        });

        txtRas.setText("Ras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(saveBTN)
                        .addGap(92, 92, 92)
                        .addComponent(tbxBTN))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLBL)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtRas)
                                .addComponent(txtAddAlien)
                                .addComponent(passLBL)
                                .addComponent(jLabel1)
                                .addComponent(dateVal)
                                .addComponent(nameVal)
                                .addComponent(dateLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(passVal, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(comboBoxRas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phoneLBL)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(platsLBL)
                                .addComponent(chefLBL)
                                .addComponent(jLabel2)
                                .addComponent(chefVal, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                .addComponent(platsVal)
                                .addComponent(phoneVal))
                            .addComponent(textVal, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(valLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAddAlien)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateLBL)
                            .addComponent(chefLBL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chefVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLBL)
                            .addComponent(platsLBL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(platsVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passLBL)
                            .addComponent(phoneLBL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(valLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxRas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBTN)
                    .addComponent(tbxBTN))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
String  val = comboBoxRas.getSelectedItem().toString();
        try {
            String name = nameVal.getText();
            String password = passVal.getText();
            String phone = phoneVal.getText();
            String date = dateVal.getText();

            // Konvertering från String till Integer.
            //int alienID = Integer.parseInt(idVal.getText());
            int chef = Integer.parseInt(chefVal.getText());
            int plats = Integer.parseInt(platsVal.getText());

            //Konvertering från JavaDate till SQLdate.
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            Date parsedate = format.parse(date);
            java.sql.Date daydate = new java.sql.Date(parsedate.getTime());

            String RasSpec = textVal.getText();
            
            try {

                String add = idb.getAutoIncrement("Alien", "Alien_ID");
                int convertID = Integer.parseInt(add);

                idb.insert("insert into ALIEN (ALIEN_ID, REGISTRERINGSDATUM, LOSENORD, NAMN, TELEFON, PLATS, ANSVARIG_AGENT)"
                        + " values ('" + add + "','" + daydate + "','" + password + "','" + name + "','" + phone + "','" + plats + "','" + chef + "')");

                JOptionPane.showMessageDialog(null, "En ny alien har registrerats med Alien-ID: " + add);
               
            
            // Beroende på vad man valt i comboboxUtrustning läggs det till i rätt tabell
            if(val.equals("Boglodite")){
                idb.insert("Insert into BOGLODITE (ALIEN_ID, ANTAL_BOOGIES) values ('" + add+ "','" + RasSpec + "')");
            }
            else if(val.equals("Squid")){
            idb.insert("Insert into SQUID (ALIEN_ID, ANTAL_ARMAR) values ('" + add + "','" + RasSpec + "')");
        
        }
            else{
                idb.insert("Insert into WORM (ALIEN_ID) values ('" + add + "')");
                    }
       
            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Något gick fel, försök igen");
                System.out.println(e.getMessage());

            }

        } catch (ParseException ex) {
            Logger.getLogger(agentAlien.class.getName()).log(Level.SEVERE, null, ex);

        }
//agentAlienB ras = new agentAlienB(idb);
  //      ras.setVisible(true);
    //   this.dispose();
      
    }//GEN-LAST:event_saveBTNActionPerformed

    private void tbxBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxBTNActionPerformed
        // TODO add your handling code here:
        AgentInloggad tbx = new AgentInloggad(idb);
        tbx.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tbxBTNActionPerformed

    private void comboBoxRasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxRasActionPerformed
        // TODO add your handling code here:
  String  val= comboBoxRas.getSelectedItem().toString();
          String fråga = textVal.getText();
         if(val.equals("Squid")){
            valLBL.setVisible(true);
            valLBL.setText("Ange antal armar:");
            textVal.setVisible(true);
            }
        else if(val.equals("Boglodite")){
            valLBL.setVisible(true);
            valLBL.setText("Ange antal boogies:");
             textVal.setVisible(true);
        }
          else{
            valLBL.setVisible(false);
            valLBL.setText("-");
            textVal.setVisible(false);
        }                             
    }//GEN-LAST:event_comboBoxRasActionPerformed

   
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agentAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agentAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agentAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agentAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chefLBL;
    private javax.swing.JTextField chefVal;
    private javax.swing.JComboBox<String> comboBoxRas;
    private javax.swing.JLabel dateLBL;
    private javax.swing.JTextField dateVal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameVal;
    private javax.swing.JLabel passLBL;
    private javax.swing.JPasswordField passVal;
    private javax.swing.JLabel phoneLBL;
    private javax.swing.JTextField phoneVal;
    private javax.swing.JLabel platsLBL;
    private javax.swing.JTextField platsVal;
    private javax.swing.JButton saveBTN;
    private javax.swing.JButton tbxBTN;
    private javax.swing.JTextField textVal;
    private javax.swing.JLabel txtAddAlien;
    private javax.swing.JLabel txtRas;
    private javax.swing.JLabel valLBL;
    // End of variables declaration//GEN-END:variables
}
