/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mib1;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author KarlJ
 */
public class AgentInloggad1 extends javax.swing.JFrame {
        private static InfDB idb;
    /**
     * Creates new form AgentInloggad1
     */
    public AgentInloggad1(InfDB idb) {
        initComponents();
        this.idb = idb;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoutBTN = new javax.swing.JButton();
        bytlösenBTN = new javax.swing.JButton();
        utrustningBTN = new javax.swing.JButton();
        områdeschefBTN = new javax.swing.JButton();
        addAlien = new javax.swing.JButton();
        updateAlien = new javax.swing.JButton();
        sökAlienBTN = new javax.swing.JButton();
        datumBTN = new javax.swing.JButton();
        lånaFordon = new javax.swing.JButton();
        lånaUtrustning = new javax.swing.JButton();
        sökAlienPlatsBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoutBTN.setText("Logga ut");
        logoutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBTNActionPerformed(evt);
            }
        });

        bytlösenBTN.setText("Byt Lösenord");
        bytlösenBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bytlösenBTNActionPerformed(evt);
            }
        });

        utrustningBTN.setText("Registrera utrustning");
        utrustningBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utrustningBTNActionPerformed(evt);
            }
        });

        områdeschefBTN.setText("Områdeschef");
        områdeschefBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                områdeschefBTNActionPerformed(evt);
            }
        });

        addAlien.setText("Registrera Alien");
        addAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAlienActionPerformed(evt);
            }
        });

        updateAlien.setText("Redigera Alien");
        updateAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAlienActionPerformed(evt);
            }
        });

        sökAlienBTN.setText("Sök Alien");
        sökAlienBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sökAlienBTNActionPerformed(evt);
            }
        });

        datumBTN.setText("Sök Alien mellan 2 datum");
        datumBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datumBTNActionPerformed(evt);
            }
        });

        lånaFordon.setText("Låna fordon");
        lånaFordon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lånaFordonActionPerformed(evt);
            }
        });

        lånaUtrustning.setText("Låna utrustning");
        lånaUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lånaUtrustningActionPerformed(evt);
            }
        });

        sökAlienPlatsBTN.setText("Sök Alien (plats)");
        sökAlienPlatsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sökAlienPlatsBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sökAlienBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bytlösenBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(områdeschefBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addAlien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(utrustningBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(sökAlienPlatsBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(updateAlien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(datumBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lånaUtrustning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lånaFordon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logoutBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAlien)
                    .addComponent(updateAlien))
                .addGap(3, 3, 3)
                .addComponent(sökAlienBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datumBTN)
                    .addComponent(sökAlienPlatsBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(utrustningBTN)
                    .addComponent(lånaUtrustning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(områdeschefBTN)
                    .addComponent(lånaFordon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bytlösenBTN)
                    .addComponent(logoutBTN))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bytlösenBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bytlösenBTNActionPerformed
        // TODO add your handling code here:
         BytLösenord nyttlösen = new BytLösenord(idb);
        nyttlösen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bytlösenBTNActionPerformed

    private void utrustningBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utrustningBTNActionPerformed
        // TODO add your handling code here:
        agentUtrustning nyUtrustning = new agentUtrustning(idb);
        nyUtrustning.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_utrustningBTNActionPerformed

    private void områdeschefBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_områdeschefBTNActionPerformed
        // TODO add your handling code here:
        
           Områdeschef chef = new Områdeschef(idb);
        chef.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_områdeschefBTNActionPerformed

    private void addAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAlienActionPerformed
        // TODO add your handling code here:
        //Tar användaren till fönstret för att registrera ny alien
         agentAlien läggTillAlien = new agentAlien(idb);
        läggTillAlien.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addAlienActionPerformed

    private void updateAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAlienActionPerformed
        // TODO add your handling code here:
        //Tar användaren till fönstret för att uppdatera en alien
       AgentUppdateraAlienA uppdateraAlien = new  AgentUppdateraAlienA(idb);
       uppdateraAlien.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_updateAlienActionPerformed

    private void sökAlienBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sökAlienBTNActionPerformed
        // TODO add your handling code here:
        //Tar användaren till sök alien fönstret
        AgentSökAlien sökAlien = new AgentSökAlien(idb);
       sökAlien.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_sökAlienBTNActionPerformed

    private void datumBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datumBTNActionPerformed
        // TODO add your handling code here:
        //Tar användaren till fönstret för att söka alien som är registrerade mellan två olika datum.
       AgentDatum alienDatum = new AgentDatum(idb);
       alienDatum.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_datumBTNActionPerformed

    private void lånaFordonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lånaFordonActionPerformed
        // TODO add your handling code here:
        //Tar användaren till fönstret för att låna fordon
        lånaFordon låna = new lånaFordon(idb);
        låna.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lånaFordonActionPerformed

    private void lånaUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lånaUtrustningActionPerformed
        // TODO add your handling code here:
        //Tar användaren till fönstret för att låna utrustning
         lånaUtrustning låna = new lånaUtrustning(idb);
        låna.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lånaUtrustningActionPerformed

    private void logoutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTNActionPerformed
        // TODO add your handling code here:
        //Tar användaren tillbaka till huvudfonster
         huvudFonster tbx = new huvudFonster(idb);
         tbx.setVisible(true);
         this.dispose();
         
    }//GEN-LAST:event_logoutBTNActionPerformed

    private void sökAlienPlatsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sökAlienPlatsBTNActionPerformed
        // TODO add your handling code here:
        //Tar användaren till sökalienplats fönster
        sökAlienPlats sök = new sökAlienPlats(idb);
        sök.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sökAlienPlatsBTNActionPerformed
   
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentInloggad1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentInloggad1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentInloggad1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentInloggad1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAlien;
    private javax.swing.JButton bytlösenBTN;
    private javax.swing.JButton datumBTN;
    private javax.swing.JButton logoutBTN;
    private javax.swing.JButton lånaFordon;
    private javax.swing.JButton lånaUtrustning;
    private javax.swing.JButton områdeschefBTN;
    private javax.swing.JButton sökAlienBTN;
    private javax.swing.JButton sökAlienPlatsBTN;
    private javax.swing.JButton updateAlien;
    private javax.swing.JButton utrustningBTN;
    // End of variables declaration//GEN-END:variables
}
